### ISSUE TITLE
[DE-790] Configuration for hostnameVerifier

### ISSUE THREAD

**Issue by osanchez-stratio** [arangodb/arangodb-spark-datasource#38]
With the java-driver, You can set this configuration:

```scala
val arangodb = new ArangoDB.Builder()
.host("localhost", 8530)
.serializer(serializer)
.password("password")
.useSsl(true)
.sslContext(sc)
.hostnameVerifier(NoopHostnameVerifier.INSTANCE)
.build
```

You can use hostnameVerifier `def` in java-driver, but in Datasource there isn't way to change the hostnameVerifier, for example not to verify hostname

**Comment by rashtao** [comment]
Since version 1.5.0, which uses Java Driver version 7, this has been changed to:
`ArangoDB.Builder#verifyHost(boolean)`.

**Comment by osanchez-stratio** [comment]
> Since version 1.5.0, which uses Java Driver version 7, this has been changed to: `ArangoDB.Builder#verifyHost(boolean)`.

And in Datasource i can set verifyHost to false?

**Comment by rashtao** [comment]
This is still an enhancement proposal, it is not implemented yet.

**Comment by vimal3271** [comment]
Is there any plan to implement this ?

**Comment by rashtao** [comment]
Yes, but delayed due to internal prioritization.
